"""Checks for the build host tooling: name resolution, unfinished output, stale locks.

These cover failures that waste an hour of somebody's build and then look like
something else: a chroot with no nameserver that dies inside pacman, an
interrupted run that leaves a file named exactly like a finished image, and a
package transaction killed mid-flight whose lock breaks the advertised resume.
"""
import fnmatch
import json
import os
import re
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASH = os.environ.get("BASH_EXE") or shutil.which("bash")
INSTALLER = (ROOT / "steamos-nvidia-installer.sh").read_text(encoding="utf-8")
COMPLETE = (ROOT / "tools" / "build-complete.sh").read_text(encoding="utf-8")
REPATCH = INSTALLER.split("<<'REPATCH'\n", 1)[1].split("\nREPATCH\n", 1)[0]
HOST_INSTALLER = INSTALLER.replace(REPATCH, "")
HELPER = re.compile(r"^set_chroot_resolver\(\) \{.*?^\}\n", re.S | re.M)


def helper_source(text):
    found = HELPER.search(text)
    assert found, "set_chroot_resolver is missing"
    return found.group(0)


def run_helper(candidates, files):
    """Source the helper on its own and let it choose a resolv.conf."""
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp) / "root"
        (root / "etc").mkdir(parents=True)
        (root / "etc" / "resolv.conf").write_text("stale\n", encoding="utf-8")
        written = []
        for name, body in files:
            path = Path(tmp) / name
            path.write_text(body, encoding="utf-8")
            written.append(str(path))
        wanted = [written[c] if isinstance(c, int) else c for c in candidates]
        script = helper_source(INSTALLER) + '\nset_chroot_resolver "$@"\n'
        result = subprocess.run([BASH, "-c", script, "test", str(root), *wanted],
                                capture_output=True, text=True, timeout=30)
        chosen = (root / "etc" / "resolv.conf").read_text(encoding="utf-8")
        return result, chosen


NO_NAMESERVER = "# Generated by a resolver that answers through NSS only\n# nothing to see here\n"
REAL_NAMESERVER = "nameserver 192.0.2.53\n"


class TheChrootGetsAWorkingResolver(unittest.TestCase):
    def test_a_host_file_with_a_nameserver_is_used_as_is(self):
        result, chosen = run_helper([0, 1], [("etc", REAL_NAMESERVER),
                                             ("fallback", "nameserver 198.51.100.53\n")])
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(chosen, REAL_NAMESERVER)

    def test_a_comment_only_host_file_falls_back(self):
        result, chosen = run_helper([0, 1], [("etc", NO_NAMESERVER), ("fallback", REAL_NAMESERVER)])
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(chosen, REAL_NAMESERVER, "the build would have died inside pacman instead")
        self.assertIn("fallback", result.stderr, "the chosen resolver should be reported")

    def test_a_commented_nameserver_does_not_count(self):
        result, chosen = run_helper([0, 1], [("etc", "#nameserver 192.0.2.53\n"),
                                             ("fallback", REAL_NAMESERVER)])
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(chosen, REAL_NAMESERVER)

    def test_no_usable_file_anywhere_fails_instead_of_continuing(self):
        result, _ = run_helper([0, 1, "/nonexistent/resolv.conf"],
                               [("etc", NO_NAMESERVER), ("fallback", NO_NAMESERVER)])
        self.assertEqual(result.returncode, 1)

    def test_a_missing_candidate_is_skipped_rather_than_fatal(self):
        result, chosen = run_helper(["/nonexistent/resolv.conf", 0], [("fallback", REAL_NAMESERVER)])
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(chosen, REAL_NAMESERVER)


class BothBuildScriptsUseTheSameHelper(unittest.TestCase):
    def test_the_two_copies_are_identical(self):
        self.assertEqual(helper_source(INSTALLER), helper_source(COMPLETE),
                         "the two copies of set_chroot_resolver have drifted apart")

    def test_neither_build_path_copies_resolv_conf_blindly(self):
        for name, text in [("steamos-nvidia-installer.sh", HOST_INSTALLER),
                           ("tools/build-complete.sh", COMPLETE)]:
            with self.subTest(script=name):
                self.assertNotIn("cp -L /etc/resolv.conf", text)
                self.assertIn("set_chroot_resolver", text)

    def test_the_systemd_resolved_files_are_offered_as_fallbacks(self):
        for text in (INSTALLER, COMPLETE):
            self.assertIn("/run/systemd/resolve/resolv.conf", text)
            self.assertIn("/run/systemd/resolve/stub-resolv.conf", text)

    def test_the_uplink_file_is_tried_before_the_stub(self):
        # The stub listener can be switched off, so the file that names the real
        # servers has to come first.
        for name, text in [("steamos-nvidia-installer.sh", INSTALLER),
                           ("tools/build-complete.sh", COMPLETE)]:
            with self.subTest(script=name):
                call = text.split("set_chroot_resolver ", 1)[1].split("||", 1)[0]
                self.assertLess(call.index("/run/systemd/resolve/resolv.conf"),
                                call.index("/run/systemd/resolve/stub-resolv.conf"))
                self.assertLess(call.index("/etc/resolv.conf"),
                                call.index("/run/systemd/resolve/resolv.conf"))

    def test_preflight_checks_both_arch_hosts(self):
        # The archive serves the pinned packages; the search resolves "latest".
        preflight = INSTALLER.split("if [[ $PREFLIGHT == 1 ]]; then", 1)[1].split("\nfi\n", 1)[0]
        self.assertIn("archive.archlinux.org", preflight)
        self.assertIn("archlinux.org/packages/search", preflight)
        self.assertIn("udevadm control --ping", preflight)
        self.assertIn("exit 0", preflight)


class AnUnfinishedImageNeverGetsTheFlashableName(unittest.TestCase):
    def test_the_build_writes_to_the_partial_name(self):
        self.assertIn('PARTIAL="${OUT%.img}.partial.img"', INSTALLER)
        self.assertIn('cp --reflink=auto "$IMG" "$PARTIAL"', INSTALLER)
        self.assertIn('LOOPDEV="$(losetup -f --show -P "$PARTIAL")"', INSTALLER)
        self.assertNotIn('cp --reflink=auto "$IMG" "$OUT"', INSTALLER)

    def test_the_final_name_appears_only_after_the_build_finished(self):
        move = 'mv -f "$PARTIAL" "$OUT"'
        self.assertIn(move, INSTALLER)
        self.assertLess(INSTALLER.index("trap - EXIT"), INSTALLER.index(move),
                        "the rename must come after cleanup, or the loop device is still attached")

    def test_a_previous_good_output_is_not_deleted_before_the_build(self):
        self.assertNotIn('warn "Removing previous output $OUT"', INSTALLER)

    def test_the_complete_builder_refuses_a_leftover_partial(self):
        self.assertIn('partial="${output%.img}.partial.img"', COMPLETE)
        self.assertIn("[[ ! -e $partial ]]", COMPLETE)


class AnInterruptedTransactionDoesNotBreakTheResume(unittest.TestCase):
    def test_a_stale_pacman_lock_discards_the_overlay(self):
        self.assertIn('if [[ -e "$UPPER/usr/lib/holo/pacmandb/db.lck" ]]; then', INSTALLER)

    def test_the_check_runs_before_the_overlay_is_mounted(self):
        self.assertLess(INSTALLER.index("pacmandb/db.lck"),
                        INSTALLER.index("mount -t overlay overlay"))

    def test_the_check_runs_after_stale_mounts_are_cleared(self):
        # Removing an upperdir while an interrupted overlay still uses it is not safe.
        self.assertLess(INSTALLER.index("Stale mount from a previous run"),
                        INSTALLER.index("pacmandb/db.lck"))


class BuildLeftoversStayOutOfGitStatus(unittest.TestCase):
    def test_the_host_probe_directory_is_ignored(self):
        probe = (ROOT / "tools" / "check-build-host.sh").read_text(encoding="utf-8")
        found = re.search(r'mktemp -d "\$work/([^"]+)"', probe)
        self.assertIsNotNone(found, "check-build-host.sh no longer creates a probe directory")
        name = found.group(1).replace("X", "a")
        patterns = [line.strip().rstrip("/") for line
                    in (ROOT / ".gitignore").read_text(encoding="utf-8").splitlines()
                    if line.strip() and not line.startswith("#")]
        self.assertTrue(any(fnmatch.fnmatch(name, pattern) for pattern in patterns),
                        ".gitignore does not cover the probe directory " + name)


class ValidatedBaselinesLiveInOneTable(unittest.TestCase):
    """Versions we have validated are data, not constants spread through scripts.

    Valve replaces the recovery image without notice, so naming one release in a
    refusal turns into a broken build for whoever downloads the current file from
    the link we ourselves publish. The builders record and warn instead.
    """

    BASELINES = json.loads((ROOT / "config" / "build-baselines.json").read_text(encoding="utf-8"))

    def test_the_table_declares_what_the_builders_read(self):
        for field in ("tested_recovery", "tested_build_root", "tested_driver"):
            self.assertIn(field, self.BASELINES)
        for version in self.BASELINES["tested_recovery"] + self.BASELINES["tested_build_root"]:
            self.assertRegex(version, r"^[0-9]+\.[0-9]+\.[0-9]+$")
        # The installer validates --driver with this expression; the default must pass it.
        self.assertRegex(self.BASELINES["tested_driver"], r"^[0-9]+(\.[0-9]+)*(-[0-9]+)?$")

    def test_the_complete_builder_records_the_baseline_instead_of_demanding_one(self):
        self.assertNotIn("Complete build currently requires SteamOS", COMPLETE)
        self.assertNotIn(r"""grep -Eq '^VERSION_ID="?3\.8\.14"?$'""", COMPLETE)
        self.assertIn("Recovery baseline: SteamOS", COMPLETE)
        self.assertIn("tested_recovery", COMPLETE)
        # The identity check is the one that must stay unconditional.
        self.assertIn("Not a SteamOS recovery image.", COMPLETE)

    def test_neither_builder_hardcodes_the_tested_driver(self):
        for name, text in [("tools/build-complete.sh", COMPLETE),
                           ("steamos-nvidia-installer.sh", HOST_INSTALLER)]:
            with self.subTest(script=name):
                self.assertIn("build-baselines.json", text)
                self.assertNotIn("driver=" + self.BASELINES["tested_driver"], text)

    def test_the_installer_no_longer_defaults_to_whatever_arch_ships_today(self):
        # tools/build-complete.sh always pinned a version; the documented plain
        # installer commands did not, so they silently followed Arch.
        self.assertNotIn("DRIVER_SPEC=latest     #", HOST_INSTALLER)
        self.assertIn("tested_driver", HOST_INSTALLER)
        self.assertIn("--driver", HOST_INSTALLER)

    def test_an_experimental_image_may_carry_the_gamescope_artifact(self):
        # pc_install_gamescope decides at install time and returns to Valve's
        # build when the versions do not match, so a build-time refusal was a
        # second lock on the same door.
        self.assertNotIn("Gamescope capture backport is for stable test images only", INSTALLER)
        support = (ROOT / "lib" / "pc-support.sh").read_text(encoding="utf-8")
        self.assertIn("pc_install_gamescope", support)
        self.assertIn('result=stock', support)


class TwoHostsBuildingOneCommitRecordTheSameMetadata(unittest.TestCase):
    """Artifact metadata must not depend on the order the filesystem lists files.

    Three builders hashed their patches and outputs straight from glob(), so the
    recorded JSON came out with its keys in directory order. The compiled binaries
    were identical across build hosts but the metadata files were not, which made
    two images from one commit impossible to compare by checksum. Measured on
    2026-09-25: 86 of 89 addon files matched between an Arch and a Bazzite build,
    and the three that did not differed only in key order.
    """

    ARTIFACT_BUILDERS = ["build-mangoapp.sh", "build-gamescope.sh",
                         "build-remote-play.sh", "build-nvenc.sh"]

    def test_every_hashed_listing_is_sorted(self):
        for name in self.ARTIFACT_BUILDERS:
            text = (ROOT / "tools" / name).read_text(encoding="utf-8")
            for number, line in enumerate(text.splitlines(), 1):
                if "glob(" not in line:
                    continue
                # Only listings whose order reaches the recorded JSON matter. The
                # licence copy loop writes each file to its own path either way.
                if "hexdigest" not in line and "sha(" not in line:
                    continue
                with self.subTest(builder=name, line=number):
                    self.assertIn("sorted(", line, line.strip())


class EveryBuilderInstallsWhatItCompilesAgainst(unittest.TestCase):
    """A builder that leans on a package an earlier builder installed is not
    independent, and this project documents building the artifacts separately.

    Measured on 2026-09-26. Building only the receiver against a fresh 3.8.14
    build root failed at the first object with "fatal error: linux/types.h: No
    such file or directory". libdrm's headers include <linux/types.h>, which
    comes from linux-api-headers. build-mangoapp.sh and build-gamescope.sh
    installed it, build-remote-play.sh and build-nvenc.sh did not, and those two
    only ever worked because tools/build-complete.sh runs them after the other
    two into the same overlay. The documented --remote-play-dir and --nvenc-dir
    flows, which take an artifact built on its own, could not work.
    """

    COMPILING_BUILDERS = ["build-mangoapp.sh", "build-gamescope.sh",
                          "build-remote-play.sh", "build-nvenc.sh"]

    @staticmethod
    def install_command(text):
        """The pacman line, with its backslash continuations joined."""
        lines = text.splitlines()
        for index, line in enumerate(lines):
            if "pacman -S " not in line:
                continue
            command = []
            while index < len(lines):
                command.append(lines[index].rstrip("\\"))
                if not lines[index].rstrip().endswith("\\"):
                    break
                index += 1
            return " ".join(command)
        return ""

    def test_every_builder_that_compiles_c_installs_the_kernel_headers(self):
        for name in self.COMPILING_BUILDERS:
            command = self.install_command((ROOT / "tools" / name).read_text(encoding="utf-8"))
            with self.subTest(builder=name):
                self.assertTrue(command, "no pacman install line found")
                self.assertIn("linux-api-headers", command)


class TheImageRecordsWhichCommitBuiltIt(unittest.TestCase):
    """Provenance has to survive being read by a different user than owns the checkout.

    Measured on 2026-09-26: the 0.1.6 candidate recorded "Source commit: unknown"
    and an empty working tree. tools/build-complete.sh runs the installer as root
    while the checkout belongs to the build user, so git refuses with "detected
    dubious ownership", the error is sent to /dev/null and the fallback wins. The
    image was then impossible to trace back to a commit.
    """

    def test_every_git_call_in_the_installer_passes_safe_directory(self):
        text = (ROOT / "steamos-nvidia-installer.sh").read_text(encoding="utf-8")
        calls = [line.strip() for line in text.splitlines()
                 if "git -C" in line and not line.strip().startswith("#")]
        self.assertTrue(calls, "the installer no longer reads the repository")
        for call in calls:
            with self.subTest(call=call):
                self.assertIn("safe.directory", call)

    def test_the_recording_still_falls_back_rather_than_failing(self):
        text = (ROOT / "steamos-nvidia-installer.sh").read_text(encoding="utf-8")
        self.assertIn("printf unknown", text)


class ContinuousIntegrationChecksEveryShellScript(unittest.TestCase):
    def test_no_shell_script_is_left_unchecked(self):
        workflow = (ROOT / ".github" / "workflows" / "checks.yml").read_text(encoding="utf-8")
        step = "\n".join(line for line in workflow.splitlines() if "shellcheck" in line)
        discovery = "ls-files " + chr(39) + "*.sh" + chr(39)
        for base, dirs, files in os.walk(ROOT):
            dirs[:] = [d for d in dirs if not d.startswith(".") and d != "__pycache__"]
            for name in sorted(files):
                if name.endswith(".sh"):
                    script = (Path(base) / name).relative_to(ROOT).as_posix()
                    with self.subTest(script=script):
                        self.assertTrue(script in step or discovery in step,
                                        script + " is not shellchecked by the workflow")

    def test_documented_tool_commands_run_through_bash(self):
        # The tools are tracked non-executable, so "sudo tools/x.sh" would not run.
        direct = re.compile(r"^\s*(?:sudo\s+)?(?:\./)?tools/\S+\.sh\b")
        for doc in sorted((ROOT / "docs" / "wiki").rglob("*.md")) + [ROOT / "README.md"]:
            for number, line in enumerate(doc.read_text(encoding="utf-8").splitlines(), 1):
                with self.subTest(doc=doc.name, line=number):
                    self.assertIsNone(direct.match(line), line.strip())


if __name__ == "__main__":
    unittest.main()


class TheOverlayDependencySurvivesAnOsUpdate(unittest.TestCase):
    """SteamOS's lib32-mangohud does not declare lib32-libxkbcommon, but its
    32-bit capsules carry a hard DT_NEEDED on libxkbcommon.so.0. The Gamescope
    session injects the overlay into every title, so on an image without that
    package any game with a 32-bit part dies with a SIGSEGV a minute or two in,
    with nothing in the GPU logs to explain it.

    The package is therefore installed twice, and the two calls are deliberately
    not alike. The build must refuse to continue without it, because the image
    would ship broken. The repair path must not, because a SteamOS update writes
    a whole new root image to the other slot and an overlay dependency must never
    be the reason an update aborts.

    Nothing guarded either call until 2026-09-26. The correction is inherited
    from upstream commit 30b40da, which predates this project's first release, so
    every image published so far carries it. This test is what keeps that true.
    """

    @staticmethod
    def install_call(text):
        """The pacman line that installs it, and the line that handles failure."""
        lines = text.splitlines()
        for index, line in enumerate(lines):
            if "lib32-libxkbcommon" in line and "pacman" in line:
                return line, lines[index + 1]
        return None, None

    def test_the_build_refuses_to_produce_an_image_without_it(self):
        call, outcome = self.install_call(HOST_INSTALLER)
        self.assertIsNotNone(call, "the image build no longer installs lib32-libxkbcommon")
        self.assertIn("die", outcome, "a missing overlay dependency would ship in the image")

    def test_the_repair_path_installs_it_but_cannot_break_an_update(self):
        call, outcome = self.install_call(REPATCH)
        self.assertIsNotNone(call, "a SteamOS update would drop it and the overlay with it")
        self.assertIn("log", outcome)
        self.assertNotIn("die", outcome, "an overlay dependency must never abort an OS update")
