"""Checks for the build host tooling: name resolution, unfinished output, stale locks.

These cover failures that waste an hour of somebody's build and then look like
something else: a chroot with no nameserver that dies inside pacman, an
interrupted run that leaves a file named exactly like a finished image, and a
package transaction killed mid-flight whose lock breaks the advertised resume.
"""
import fnmatch
import os
import re
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASH = os.environ.get("BASH_EXE") or shutil.which("bash")
INSTALLER = (ROOT / "steamos-nvidia-installer.sh").read_text(encoding="utf-8")
COMPLETE = (ROOT / "tools" / "build-complete.sh").read_text(encoding="utf-8")
REPATCH = INSTALLER.split("<<'REPATCH'\n", 1)[1].split("\nREPATCH\n", 1)[0]
HOST_INSTALLER = INSTALLER.replace(REPATCH, "")
HELPER = re.compile(r"^set_chroot_resolver\(\) \{.*?^\}\n", re.S | re.M)


def helper_source(text):
    found = HELPER.search(text)
    assert found, "set_chroot_resolver is missing"
    return found.group(0)


def run_helper(candidates, files):
    """Source the helper on its own and let it choose a resolv.conf."""
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp) / "root"
        (root / "etc").mkdir(parents=True)
        (root / "etc" / "resolv.conf").write_text("stale\n", encoding="utf-8")
        written = []
        for name, body in files:
            path = Path(tmp) / name
            path.write_text(body, encoding="utf-8")
            written.append(str(path))
        wanted = [written[c] if isinstance(c, int) else c for c in candidates]
        script = helper_source(INSTALLER) + '\nset_chroot_resolver "$@"\n'
        result = subprocess.run([BASH, "-c", script, "test", str(root), *wanted],
                                capture_output=True, text=True, timeout=30)
        chosen = (root / "etc" / "resolv.conf").read_text(encoding="utf-8")
        return result, chosen


NO_NAMESERVER = "# Generated by a resolver that answers through NSS only\n# nothing to see here\n"
REAL_NAMESERVER = "nameserver 192.0.2.53\n"


class TheChrootGetsAWorkingResolver(unittest.TestCase):
    def test_a_host_file_with_a_nameserver_is_used_as_is(self):
        result, chosen = run_helper([0, 1], [("etc", REAL_NAMESERVER),
                                             ("fallback", "nameserver 198.51.100.53\n")])
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(chosen, REAL_NAMESERVER)

    def test_a_comment_only_host_file_falls_back(self):
        result, chosen = run_helper([0, 1], [("etc", NO_NAMESERVER), ("fallback", REAL_NAMESERVER)])
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(chosen, REAL_NAMESERVER, "the build would have died inside pacman instead")
        self.assertIn("fallback", result.stderr, "the chosen resolver should be reported")

    def test_a_commented_nameserver_does_not_count(self):
        result, chosen = run_helper([0, 1], [("etc", "#nameserver 192.0.2.53\n"),
                                             ("fallback", REAL_NAMESERVER)])
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(chosen, REAL_NAMESERVER)

    def test_no_usable_file_anywhere_fails_instead_of_continuing(self):
        result, _ = run_helper([0, 1, "/nonexistent/resolv.conf"],
                               [("etc", NO_NAMESERVER), ("fallback", NO_NAMESERVER)])
        self.assertEqual(result.returncode, 1)

    def test_a_missing_candidate_is_skipped_rather_than_fatal(self):
        result, chosen = run_helper(["/nonexistent/resolv.conf", 0], [("fallback", REAL_NAMESERVER)])
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(chosen, REAL_NAMESERVER)


class BothBuildScriptsUseTheSameHelper(unittest.TestCase):
    def test_the_two_copies_are_identical(self):
        self.assertEqual(helper_source(INSTALLER), helper_source(COMPLETE),
                         "the two copies of set_chroot_resolver have drifted apart")

    def test_neither_build_path_copies_resolv_conf_blindly(self):
        for name, text in [("steamos-nvidia-installer.sh", HOST_INSTALLER),
                           ("tools/build-complete.sh", COMPLETE)]:
            with self.subTest(script=name):
                self.assertNotIn("cp -L /etc/resolv.conf", text)
                self.assertIn("set_chroot_resolver", text)

    def test_the_systemd_resolved_files_are_offered_as_fallbacks(self):
        for text in (INSTALLER, COMPLETE):
            self.assertIn("/run/systemd/resolve/resolv.conf", text)
            self.assertIn("/run/systemd/resolve/stub-resolv.conf", text)

    def test_the_uplink_file_is_tried_before_the_stub(self):
        # The stub listener can be switched off, so the file that names the real
        # servers has to come first.
        for name, text in [("steamos-nvidia-installer.sh", INSTALLER),
                           ("tools/build-complete.sh", COMPLETE)]:
            with self.subTest(script=name):
                call = text.split("set_chroot_resolver ", 1)[1].split("||", 1)[0]
                self.assertLess(call.index("/run/systemd/resolve/resolv.conf"),
                                call.index("/run/systemd/resolve/stub-resolv.conf"))
                self.assertLess(call.index("/etc/resolv.conf"),
                                call.index("/run/systemd/resolve/resolv.conf"))

    def test_preflight_checks_both_arch_hosts(self):
        # The archive serves the pinned packages; the search resolves "latest".
        preflight = INSTALLER.split("if [[ $PREFLIGHT == 1 ]]; then", 1)[1].split("\nfi\n", 1)[0]
        self.assertIn("archive.archlinux.org", preflight)
        self.assertIn("archlinux.org/packages/search", preflight)
        self.assertIn("udevadm control --ping", preflight)
        self.assertIn("exit 0", preflight)


class AnUnfinishedImageNeverGetsTheFlashableName(unittest.TestCase):
    def test_the_build_writes_to_the_partial_name(self):
        self.assertIn('PARTIAL="${OUT%.img}.partial.img"', INSTALLER)
        self.assertIn('cp --reflink=auto "$IMG" "$PARTIAL"', INSTALLER)
        self.assertIn('LOOPDEV="$(losetup -f --show -P "$PARTIAL")"', INSTALLER)
        self.assertNotIn('cp --reflink=auto "$IMG" "$OUT"', INSTALLER)

    def test_the_final_name_appears_only_after_the_build_finished(self):
        move = 'mv -f "$PARTIAL" "$OUT"'
        self.assertIn(move, INSTALLER)
        self.assertLess(INSTALLER.index("trap - EXIT"), INSTALLER.index(move),
                        "the rename must come after cleanup, or the loop device is still attached")

    def test_a_previous_good_output_is_not_deleted_before_the_build(self):
        self.assertNotIn('warn "Removing previous output $OUT"', INSTALLER)

    def test_the_complete_builder_refuses_a_leftover_partial(self):
        self.assertIn('partial="${output%.img}.partial.img"', COMPLETE)
        self.assertIn("[[ ! -e $partial ]]", COMPLETE)


class AnInterruptedTransactionDoesNotBreakTheResume(unittest.TestCase):
    def test_a_stale_pacman_lock_discards_the_overlay(self):
        self.assertIn('if [[ -e "$UPPER/usr/lib/holo/pacmandb/db.lck" ]]; then', INSTALLER)

    def test_the_check_runs_before_the_overlay_is_mounted(self):
        self.assertLess(INSTALLER.index("pacmandb/db.lck"),
                        INSTALLER.index("mount -t overlay overlay"))

    def test_the_check_runs_after_stale_mounts_are_cleared(self):
        # Removing an upperdir while an interrupted overlay still uses it is not safe.
        self.assertLess(INSTALLER.index("Stale mount from a previous run"),
                        INSTALLER.index("pacmandb/db.lck"))


class BuildLeftoversStayOutOfGitStatus(unittest.TestCase):
    def test_the_host_probe_directory_is_ignored(self):
        probe = (ROOT / "tools" / "check-build-host.sh").read_text(encoding="utf-8")
        found = re.search(r'mktemp -d "\$work/([^"]+)"', probe)
        self.assertIsNotNone(found, "check-build-host.sh no longer creates a probe directory")
        name = found.group(1).replace("X", "a")
        patterns = [line.strip().rstrip("/") for line
                    in (ROOT / ".gitignore").read_text(encoding="utf-8").splitlines()
                    if line.strip() and not line.startswith("#")]
        self.assertTrue(any(fnmatch.fnmatch(name, pattern) for pattern in patterns),
                        ".gitignore does not cover the probe directory " + name)


class ContinuousIntegrationChecksEveryShellScript(unittest.TestCase):
    def test_no_shell_script_is_left_unchecked(self):
        workflow = (ROOT / ".github" / "workflows" / "checks.yml").read_text(encoding="utf-8")
        step = "\n".join(line for line in workflow.splitlines() if "shellcheck" in line)
        discovery = "ls-files " + chr(39) + "*.sh" + chr(39)
        for base, dirs, files in os.walk(ROOT):
            dirs[:] = [d for d in dirs if not d.startswith(".") and d != "__pycache__"]
            for name in sorted(files):
                if name.endswith(".sh"):
                    script = (Path(base) / name).relative_to(ROOT).as_posix()
                    with self.subTest(script=script):
                        self.assertTrue(script in step or discovery in step,
                                        script + " is not shellchecked by the workflow")

    def test_documented_tool_commands_run_through_bash(self):
        # The tools are tracked non-executable, so "sudo tools/x.sh" would not run.
        direct = re.compile(r"^\s*(?:sudo\s+)?(?:\./)?tools/\S+\.sh\b")
        for doc in sorted((ROOT / "docs" / "wiki").rglob("*.md")) + [ROOT / "README.md"]:
            for number, line in enumerate(doc.read_text(encoding="utf-8").splitlines(), 1):
                with self.subTest(doc=doc.name, line=number):
                    self.assertIsNone(direct.match(line), line.strip())


if __name__ == "__main__":
    unittest.main()
